apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31112
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "php-app"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: php
        image: dapr-state-management-examples-php-http:latest  
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_KEY
          value: "base64:NhBNyadmoOUBv4FX3YSwsl8akMOWfAiDkapyP5LK3jA="
          # Turn to "true" for debugging
        - name: APP_DEBUG
          value: "false"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"