apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31116
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "java-app"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: java
        image: dapr-state-management-examples-java-sdk:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"