apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-sdk
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31112
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
    app: dotnet-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-sdk
  template:
    metadata:
      labels:
        app: dotnet-sdk
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dotnet-sdk"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: dotnet-sdk
        image: dapr-state-management-examples-dotnet-sdk:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
